---
title: "Conservation Agents Leaderboard"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: 
      bootswatch: cosmo
      
    source_code: "https://github.com/eco4cast/neon4cast-dashboard"
    navbar:
    - { title: "Fishing", href: "fishing.html", target: "_blank"}
    - { title: "Conservation", href: "conservation.html", target: "_blank"}
    - { title: "Climate", href: "climate.html", target: "_blank"}
    - { title: "Wildfire", href: "wildfire.html", target: "_blank"}
    - { title: "Epidemics", href: "epidemics.html", target: "_blank"}
---
```{r, include=FALSE}
library(dplyr)
library(flexdashboard)
library(DT)
library(crosstalk)
source("utils.R")

conservation_leaderboard <- select_gym_leaderboard("Gym Conservation")
```   


Column {.tabset}
-------------------------------------
   
### conservation-v0

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v0')
```


### conservation-v1

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v1')
```


### conservation-v2

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v2')
```


### conservation-v3

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v3')
```


### conservation-v4

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v4')
```


### conservation-v5

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v5')
```


### conservation-v6

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v6')
```


### conservation-v7

```{r} 
display_env_leaderboard(conservation_leaderboard, 'conservation-v7')
```


