---
title: "Conservation Agents Leaderboard"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: 
      bootswatch: cosmo
      
    navbar:
    - { title: "Fishing", href: "fishing.html", target: "_blank"}
    - { title: "Conservation", href: "conservation.html", target: "_blank"}
    - { title: "Climate", href: "climate.html", target: "_blank"}
    - { title: "Wildfire", href: "wildfire.html", target: "_blank"}
    - { title: "Epidemics", href: "epidemic.html", target: "_blank"}
    - { title: "Submit Agent", href: "https://forms.gle/tdVmyo4JD7cS4Goo7", 
        target: "_blank", icon: "fa fa-paper-plane"}
    - {icon: "fab fa-github", href: "https://github.com/boettiger-lab/rl-leaderboard",
        target: "_blank"}
---
```{r, include=FALSE}
library(dplyr)
library(flexdashboard)
library(DT)
library(crosstalk)
library(reticulate)
source("utils.R")

fishing_leaderboard <- select_gym_leaderboard("Gym Fishing")
```

Column {.tabset}
-------------------------------------

### Home

Welcome to the Conservation Agents Leaderboard.<br /><br />On this left side-panel, context is provided for the environments from the [Fishing Gym](https://github.com/boettiger-lab/gym_fishing). The right side-panel hosts the leaderboard where submitted agents are evaluated.

### fishing-v0

This environment implements a simple, single species logistic growth-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow a logistic growth model.

**Action Space** The agent selects the amount of fish to harvest with respect to K. In this case, at interval of K/100ths: 0, K/100, K/50, 3K/100, K/25, ...

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step.

### fishing-v1

This environment implements a simple, single species logistic growth-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow a logistic growth model.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step.

### fishing-v2

This environment implements a single species logistic growth-based fishery with a tipping point.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow a logistic growth model but below a population of 0.5K the population becomes much more likely to crash.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step.


### fishing-v4

This environment implements a single species logistic growth-based fishery with model error.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow a logistic growth model but with an `r` and `K` that are drawn from a normal distribution each episode.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step.

### fishing-v5

This environment implements a single species Allen model-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow the Allen growth model.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step.

### fishing-v6

This environment implements a single species Beverton-Holt model-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow the Beverton-Holt growth model.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step. 

### fishing-v7

This environment implements a single species May model-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow the May growth model.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step. 

### fishing-v8

This environment implements a single species Myers model-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow the Myers growth model.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step. 

### fishing-v9

This environment implements a single species Ricker model-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow the Ricker model.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step. 

### fishing-v10

This environment implements a single species non-stationary Beverton-Holt model-based fishery.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Dynamics follow a Beverton-Holt growth model where `r` changes constantly over an episode by some amount, `alpha`.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step. 

### fishing-v11

This environment implements a fishery where the transition dynamics vary each episode.

**Observation Space** The agent observes the fish population at that time step.

**Model Dynamics** Transition dynamics can follow May, Ricker, Allen, Beverton-Holt or Myers growth models. The dynamics model is randomly chosen every episode.

**Action Space** The agent selects a quantity of fish to harvest with respect to K with a continuous interval.

**Reward Function** The agent is rewarded by the amount of fish harvested at a time step. 

Column {.tabset}
-------------------------------------
   
### fishing-v0 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v0')
``` 

### fishing-v1 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v1')
``` 


### fishing-v2 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v2')
``` 


### fishing-v4 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v4')
``` 


### fishing-v5 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v5')
``` 


### fishing-v6 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v6')
``` 


### fishing-v7 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v7')
``` 


### fishing-v8 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v8')
``` 


### fishing-v9 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v9')
``` 


### fishing-v10 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v10')
``` 


### fishing-v11 

```{r} 
display_env_leaderboard(fishing_leaderboard, 'fishing-v11')
``` 