rmarkdown::render("fishing.Rmd", envir = globalenv())
rmarkdown::render("climate.Rmd", envir = globalenv())
rmarkdown::render("epidemic.Rmd", envir = globalenv())
rmarkdown::render("conservation.Rmd", envir = globalenv())
rmarkdown::render("wildfire.Rmd", envir = globalenv())
